name: Test Compilazione # Action name
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Download file della Repo
        uses: actions/checkout@v3
      - name: Compilazione dei file
        uses: xu-cheng/latex-action@v3
        with: # insert here files to compile
          working_directory: Stickers_Album
          root_file: |
            Stickers_Album.tex
            Stickers.tex
      - name: Ridenominazione files
        run: |
          mv Stickers_Album/Stickers_Album.pdf Stickers_Album/Album_di_Figurine.pdf
          mv Stickers_Album/Stickers.pdf Stickers_Album/Figurine.pdf
      - name: Caricamento della Release temporanea
        uses: actions/upload-artifact@v3
        with: 
          name: Album&Stickers
          path: |
            Stickers_Album/Album_di_Figurine.pdf
            Stickers_Album/Figurine.pdf
