name: Test Compilazione # Action name
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Download file della Repo
        uses: actions/checkout@v3
      - name: Compilazione dei file
        uses: xu-cheng/latex-action@v2
        with: # insert here files to compile
          working_directory: Stickers_Album
          root_file: Stickers_Album.tex
      - name: Caricamento della Release temporanea
        uses: actions/upload-artifact@v3
        with: 
          name: Album
          path: Stickers_Album.pdf
